name: Test coverage

on:
  workflow_run:
    workflows: ["Python tests"]
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: faketoken
