name: Python tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.2"
      - name: Install dependencies
        run: poetry install
      - name: Run tests and generate coverage report
        run: poetry run coverage run -m pytest
      - name: Generate coverage report
        run: poetry run coverage xml coverage.xml
      - name: Publish coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install tox and other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
